Repository Benjo6/Exam-CPHMTOGO, pull requests merged in 2022-11, with the labels that each got.

#48 Authentication service
  CPHMTOGO/.idea/.idea.AuthenticationMicroService/.idea/workspace.xml
  CPHMTOGO/.idea/.idea.CPHMTOGO/.idea/.gitignore
  CPHMTOGO/.idea/.idea.CPHMTOGO/.idea/aws.xml
  CPHMTOGO/.idea/.idea.CPHMTOGO/.idea/dictionaries
  CPHMTOGO/.idea/.idea.CPHMTOGO/.idea/indexLayout.xml
  CPHMTOGO/.idea/.idea.CPHMTOGO/.idea/misc.xml
  CPHMTOGO/.idea/.idea.CPHMTOGO/.idea/vcs.xml
  CPHMTOGO/.idea/.idea.MicroServices/.idea/.gitignore
  CPHMTOGO/.idea/.idea.MicroServices/.idea/.name
  CPHMTOGO/.idea/.idea.MicroServices/.idea/aws.xml
  CPHMTOGO/.idea/.idea.MicroServices/.idea/dictionaries
  CPHMTOGO/.idea/.idea.MicroServices/.idea/indexLayout.xml
  CPHMTOGO/.idea/.idea.MicroServices/.idea/misc.xml
  CPHMTOGO/.idea/config/applicationhost.config
  CPHMTOGO/API Gateway/APIGateway.csproj
  CPHMTOGO/API Gateway/Controllers/AuthenticationController.cs
  CPHMTOGO/API Gateway/Controllers/GrpcControllerBase.cs
  CPHMTOGO/API Gateway/Program.cs
  CPHMTOGO/API Gateway/Properties/launchSettings.json
  CPHMTOGO/API Gateway/appsettings.Development.json
  CPHMTOGO/API Gateway/appsettings.json
  CPHMTOGO/Authentication Service/Application/AuthenticationApplicationRepository.cs
  CPHMTOGO/Authentication Service/Application/Contracts/Commands/ChangePasswordCommand.cs
  CPHMTOGO/Authentication Service/Application/Contracts/Commands/SignInCommand.cs
  CPHMTOGO/Authentication Service/Application/Contracts/Commands/SignUpCommand.cs
  CPHMTOGO/Authentication Service/Application/IAuthenticationApplicationRepository.cs
  CPHMTOGO/Authentication Service/AuthenticationService.csproj
  CPHMTOGO/Authentication Service/Domain/LoginInfo.cs
  CPHMTOGO/Authentication Service/Infrastructure/AuthenticationDbContext.cs
  CPHMTOGO/Authentication Service/Program.cs
  CPHMTOGO/Authentication Service/Properties/launchSettings.json
  CPHMTOGO/Authentication Service/Protos/authentication.proto
  CPHMTOGO/Authentication Service/Service/AuthenticationService.cs
  CPHMTOGO/Authentication Service/ServiceProfile.cs
  CPHMTOGO/Authentication Service/appsettings.Development.json
  CPHMTOGO/Authentication Service/appsettings.json
  CPHMTOGO/CPHMTOGO.sln
  CPHMTOGO/TestZone/AuthenticationMSUnitTest/AuthenticationServiceUnitTest.csproj
  CPHMTOGO/TestZone/AuthenticationMSUnitTest/UnitTest1.cs
  CPHMTOGO/TestZone/AuthenticationMSUnitTest/Usings.cs
  Infrastructure/docker/docker-compose.applications.yml
  Infrastructure/docker/docker-compose.yml
Labels: feature

#50 feature: unittest and integrationtest
  CPHMTOGO/API Gateway/Controllers/AuthenticationController.cs
  CPHMTOGO/Authentication Service/Application/AuthenticationApplicationRepository.cs
  CPHMTOGO/Authentication Service/AuthenticationService.csproj
  CPHMTOGO/Authentication Service/Domain/LoginInfo.cs
  CPHMTOGO/Authentication Service/Infrastructure/AuthenticationDbContext.cs
  CPHMTOGO/Authentication Service/Program.cs
  CPHMTOGO/Authentication Service/appsettings.json
  CPHMTOGO/CPHMTOGO.sln
  CPHMTOGO/TestZone/AuthenticationMSUnitTest/AuthenticationServiceUnitTest.csproj
  CPHMTOGO/TestZone/AuthenticationMSUnitTest/UnitTest1.cs
  CPHMTOGO/TestZone/AuthenticationServiceTests/AuthenticationServiceTests.csproj
  CPHMTOGO/TestZone/AuthenticationServiceTests/IntegrationTest/IntegrationTest.cs
  CPHMTOGO/TestZone/AuthenticationServiceTests/UnitTest/UnitTest.cs
  CPHMTOGO/TestZone/AuthenticationServiceTests/Usings.cs
  start-bash.txt
Labels: documentation, enhancement

#56 Database
  user-service/.env
  user-service/package-lock.json
  user-service/package.json
  user-service/prisma/ERD.svg
  user-service/prisma/migrations/20221114220332_init/migration.sql
  user-service/prisma/migrations/migration_lock.toml
  user-service/prisma/schema.prisma
  user-service/tsconfig.json
Labels: fix

#60 User service
  .circleci/config.yml
  README.md
Labels: fix
