Repository Benjo6/Exam-CPHMTOGO, pull requests merged in 2022-12, with the labels that each got.

#65 Restaurant service
  .circleci/config.yml
  CPHMTOGO/RestaurantService/.env
  CPHMTOGO/RestaurantService/.eslintrc.cjs
  CPHMTOGO/RestaurantService/controllers/menu.controller.ts
  CPHMTOGO/RestaurantService/controllers/menuItem.controller.ts
  CPHMTOGO/RestaurantService/controllers/restaurant.controller.ts
  CPHMTOGO/RestaurantService/coverage/clover.xml
  CPHMTOGO/RestaurantService/coverage/coverage-final.json
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/controllers/index.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/controllers/menu.controller.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/controllers/menuItem.controller.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/controllers/restaurant.controller.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/index.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/prisma/client.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/prisma/index.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/resolvers/index.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/resolvers/resolver.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/server.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/typeDefs/index.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/RestaurantService/typeDefs/typeDefs.ts.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/base.css
  CPHMTOGO/RestaurantService/coverage/lcov-report/block-navigation.js
  CPHMTOGO/RestaurantService/coverage/lcov-report/favicon.png
  CPHMTOGO/RestaurantService/coverage/lcov-report/index.html
  CPHMTOGO/RestaurantService/coverage/lcov-report/prettify.css
  CPHMTOGO/RestaurantService/coverage/lcov-report/prettify.js
  CPHMTOGO/RestaurantService/coverage/lcov-report/sort-arrow-sprite.png
  CPHMTOGO/RestaurantService/coverage/lcov-report/sorter.js
  CPHMTOGO/RestaurantService/coverage/lcov.info
  CPHMTOGO/RestaurantService/interfaces/menu.interface.ts
  CPHMTOGO/RestaurantService/interfaces/menuItem.interface.ts
  CPHMTOGO/RestaurantService/interfaces/restaurant.interface.ts
  CPHMTOGO/RestaurantService/jest.config.js
  CPHMTOGO/RestaurantService/package.json
  CPHMTOGO/RestaurantService/prisma/client.ts
  CPHMTOGO/RestaurantService/prisma/migrations/20221123173344_init/migration.sql
  CPHMTOGO/RestaurantService/prisma/migrations/20221123181942_init/migration.sql
  CPHMTOGO/RestaurantService/prisma/migrations/migration_lock.toml
  CPHMTOGO/RestaurantService/prisma/schema.prisma
  CPHMTOGO/RestaurantService/resolvers/resolver.ts
  CPHMTOGO/RestaurantService/server.ts
  CPHMTOGO/RestaurantService/singleton.ts
  CPHMTOGO/RestaurantService/test/unit/example.test.ts
  CPHMTOGO/RestaurantService/tsconfig.json
  CPHMTOGO/RestaurantService/typeDefs/typeDefs.ts
  CPHMTOGO/RestaurantService/yarn.lock
Labels: enhancement, feature

#67 Address service
  .circleci/config.yml
  CPHMTOGO/Address.cs
  CPHMTOGO/AddressContext.cs
  CPHMTOGO/AddressController.cs
  CPHMTOGO/AddressDto.cs
  CPHMTOGO/AddressRepository.cs
  CPHMTOGO/AddressService.cs
  CPHMTOGO/AddressService/AddressService.csproj
  CPHMTOGO/AddressService/Controllers/AddressController.cs
  CPHMTOGO/AddressService/Domain/Address.cs
  CPHMTOGO/AddressService/Domain/Dto/AddressDto.cs
  CPHMTOGO/AddressService/Infrastructure/AddressDbContext.cs
  CPHMTOGO/AddressService/IoC/ServiceRegistry.cs
  CPHMTOGO/AddressService/Profile/AddressProfile.cs
  CPHMTOGO/AddressService/Program.cs
  CPHMTOGO/AddressService/Properties/launchSettings.json
  CPHMTOGO/AddressService/Repositories/AddressRepository.cs
  CPHMTOGO/AddressService/Repositories/IAddressRepository.cs
  CPHMTOGO/AddressService/Services/AddressService.cs
  CPHMTOGO/AddressService/Services/IAddressService.cs
  CPHMTOGO/AddressService/appsettings.Development.json
  CPHMTOGO/AddressService/appsettings.json
  CPHMTOGO/CPHMTOGO.sln
  CPHMTOGO/Core/Properties/launchSettings.json
  CPHMTOGO/IAddressRepository.cs
  CPHMTOGO/IAddressService.cs
Labels: enhancement, feature

#71 Restaurant service
  CPHMTOGO/RestaurantService/controllers/restaurant.controller.ts
  CPHMTOGO/RestaurantService/interfaces/restaurant.interface.ts
  CPHMTOGO/RestaurantService/prisma/migrations/20221225104245_init/migration.sql
  CPHMTOGO/RestaurantService/prisma/schema.prisma
  CPHMTOGO/RestaurantService/resolvers/resolver.ts
  CPHMTOGO/RestaurantService/typeDefs/typeDefs.ts
  Infrastructure/docker/init/restaurants/init.sql
Labels: fix

#72 User service
  CPHMTOGO/RestaurantService/controllers/restaurant.controller.ts
  CPHMTOGO/UserService/coverage/clover.xml
  CPHMTOGO/UserService/coverage/coverage-final.json
  CPHMTOGO/UserService/coverage/lcov-report/index.html
  CPHMTOGO/UserService/coverage/lcov-report/src/controllers/company.controller.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/controllers/customer.controller.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/controllers/employee.controller.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/controllers/index.html
  CPHMTOGO/UserService/coverage/lcov-report/src/index.html
  CPHMTOGO/UserService/coverage/lcov-report/src/models/company.model.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/models/customer.model.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/models/employee.model.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/models/index.html
  CPHMTOGO/UserService/coverage/lcov-report/src/routes/company.routes.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/routes/customer.routes.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/routes/employee.routes.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/routes/index.html
  CPHMTOGO/UserService/coverage/lcov-report/src/server.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/utils/checkUuid.ts.html
  CPHMTOGO/UserService/coverage/lcov-report/src/utils/index.html
  CPHMTOGO/UserService/coverage/lcov.info
  CPHMTOGO/UserService/package.json
  CPHMTOGO/UserService/prisma/migrations/20221211021057_init/migration.sql
  CPHMTOGO/UserService/prisma/migrations/migration_lock.toml
  CPHMTOGO/UserService/prisma/schema.prisma
  CPHMTOGO/UserService/src/Untitled-1.ts
  CPHMTOGO/UserService/src/controllers/company.controller.ts
  CPHMTOGO/UserService/src/controllers/customer.controller.ts
  CPHMTOGO/UserService/src/controllers/employee.controller.ts
  CPHMTOGO/UserService/src/interfaces/employee.interface.ts
  CPHMTOGO/UserService/src/models/customer.model.ts
  CPHMTOGO/UserService/src/models/employee.model.ts
  CPHMTOGO/UserService/src/server.ts
  CPHMTOGO/UserService/test/unit/employee.test.ts
  CPHMTOGO/UserService/yarn.lock
  CPHMTOGO/emailService/yarn.lock
Labels: feature, fix

#73 fixed init.sql files for users and restaurants
  CPHMTOGO/UserService/prisma/migrations/20221225113243_init/migration.sql
  Infrastructure/docker/init/restaurants/init.sql
  Infrastructure/docker/init/users/init.sql
Labels: fix

#77 All functionalities working.
  CPHMTOGO/API Gateway/APIGateway.csproj
  CPHMTOGO/API Gateway/Controllers/AuthenticationController.cs
  CPHMTOGO/API Gateway/Controllers/OrderController.cs
  CPHMTOGO/API Gateway/Dockerfile
  CPHMTOGO/API Gateway/Program.cs
  CPHMTOGO/API Gateway/appsettings.json
  CPHMTOGO/AuthenticationService/Application/AuthenticationApplicationRepository.cs
  CPHMTOGO/AuthenticationService/Application/Contracts/Commands/LoginInfoCommand.cs
  CPHMTOGO/AuthenticationService/Application/IAuthenticationApplicationRepository.cs
  CPHMTOGO/AuthenticationService/Protos/authentication.proto
  CPHMTOGO/AuthenticationService/Service/AuthenticationService.cs
  CPHMTOGO/AuthenticationService/ServiceProfile.cs
  Infrastructure/cphmtogo/docker-compose.infrastructure.prod.yml
Labels: bug
